Solutions of the second contest
VazheninAlex/aboba_307_11 pull request #1
Opened 2023-11-03 07:53 UTC by VazheninAlex

2023-11-08 22:02 UTC, mr3vial requested changes
Так как реквест идёт на все задачи, то и задачи будут приняты в случае, если со всеми будет ОК

2023-11-08 22:02 UTC, mr3vial commented on C.cpp
> +  }
Требуется декомпозиция, разделение логики на функции с последующим выносом из `main`

2023-11-08 22:02 UTC, mr3vial commented on D.cpp
> +#define magic 1000000000
Лучше через явное объявление константы, а не `#define`

2023-11-08 22:02 UTC, mr3vial commented on D.cpp
> +};
https://google.github.io/styleguide/cppguide.html#Declaration_Order — сначала `public:`, затем `protected:`, затем `private:`

2023-11-08 22:02 UTC, mr3vial commented on D.cpp
> +    }
Что будет, если появятся новые команды, которые начинаются на уже занятые буквы?

2023-11-08 22:02 UTC, mr3vial commented on D.cpp
> +  void Decueue() {
`Dequeue`

https://google.github.io/styleguide/cppguide.html#Punctuation,_Spelling_and_Grammar

2023-11-08 22:02 UTC, mr3vial commented on D.cpp
> +  std::stack<std::pair<int, int>> iq2_;
Что такое `iq1_` и `iq2_`? По названию переменных сразу не ясно, за что они отвечают.

2023-11-08 22:02 UTC, mr3vial commented on D.cpp
> + private:
https://google.github.io/styleguide/cppguide.html#Declaration_Order — `public:` -> `protected:` -> `private:`

2023-11-08 22:02 UTC, mr3vial commented on F.cpp
> +struct Heap {
Ответ на вопрос, когда нужен класс, а когда достаточно структуры: https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes

Судя по всему, здесь нужен именно класс.

2023-11-08 22:02 UTC, mr3vial commented on F.cpp
> + private:
https://google.github.io/styleguide/cppguide.html#Declaration_Order

2023-11-08 22:02 UTC, mr3vial commented on F.cpp
> +      for (long long j = (1 << 3) - 1; j < static_cast<long long>(input.size());
Интересно, зачем нам именно `1 << 3` и `1 << 4` в дальнейшем? Просто не совсем понятно, зачем нам вдруг это понадобилось

2023-11-08 22:02 UTC, mr3vial commented on F.cpp
> +    }
Тот же вопрос про расширяемость команд

2023-11-08 22:02 UTC, mr3vial commented on H.cpp
> +#define magic 30
Лучше константы использовать

2023-11-08 22:02 UTC, mr3vial commented on H.cpp
> +};
Аналогично предыдущим задачам

2023-11-08 22:02 UTC, mr3vial commented on H.cpp
> +  void Iinsert(long long val, long long index) {
Не совсем ясно, зачем __везде__ удваивать первую букву в названии метода.

2023-11-08 22:02 UTC, mr3vial commented on H.cpp
> +  }
Вопросы те же, что и в F

2023-11-10 18:57 UTC, VazheninAlex commented
Вроде, исправил недочеты.

2023-11-12 17:03 UTC, mr3vial approved these changes

2023-11-12 17:03 UTC, merged